# Generated by Django 6.0.4 on 2026-06-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_homepage_project_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='About Us', max_length=200)),
                ('introduction', models.TextField()),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
                ('impact', models.TextField()),
                ('why_choose_us', models.TextField(help_text='One reason per line')),
                ('process', models.TextField(help_text='One step per line')),
                ('ceo_name', models.CharField(max_length=100)),
                ('ceo_bio', models.TextField()),
                ('ceo_image', models.ImageField(blank=True, null=True, upload_to='about/')),
            ],
        ),
    ]
